export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST"
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS"
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL"

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST"
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS"
export const POST_DELETE_FAIL = "POST_DELETE_FAIL"